---
title: 'Exercise 2_2_2: Define your Cases'
author: 'Johannes Breuer, Stefan Jünger'
date: 'Introduction to R for Data Analysis'
---

```{r child = "../config/exercises_setup.Rmd"}
```

```{r read-data, message = F}
library(tidyverse)
library(sjlabelled)

gp_covid <- 
  read_csv2("./data/ZA5667_v1-1-0.csv") %>%
  set_na(na = c(-99, -77, -33, 98))
```

```{block, box.title = "1", box.body = list(fill = "white"), box.icon = "fa-star"}
Create a new binary variable called `married` in the `gp_covid` dataframe that has the value 1 if the individual is married and 0 if not. 
```

```{block, opts.label = "clues"}
As there are no missing values in the variable, you can simply use `ifelse()` for this.
```

```{r first-exercise, solution = TRUE}
gp_covid <- gp_covid %>% 
  mutate(married = ifelse(marstat == 1, 1, 0))
```

```{block, box.title = "2", box.body = list(fill = "white"), box.icon = "fa-star"}
Let's create another new variable. This time, it should be a character variable named `age_3cat` that has the following unique values representing the respective age categories: "up to 40 years", "41 to 60 years" and "older than 60 years".
```

```{block, opts.label = "clues"}
You can use the `between()` helper function in combination with the `dplyr` function for conditional variable creation/transformation. The required existing variable is called `age_cat`. As a side note: In reality, you would probably would want to have such a variable as an ordered factor, but for the sake of simplicity, we'll stick with character variable here.
```

```{r second-exercise, solution = TRUE}
gp_covid <- gp_covid %>% 
  mutate(age_3cat = case_when(
    between(age_cat, 1, 4) ~ "up to 40 years",
    between(age_cat, 5, 7) ~ "41 to 60 years",
    age_cat > 7 ~ "older than 60 years"
    ))
```
