---
title: 'Exercise 1_1_2: Packages & Scripts'
author: 'Johannes Breuer, Stefan Jünger'
date: 'Introduction to R for Data Analysis'
---

```{r child = "../config/exercises_setup.Rmd"}
```

For this set of exercises as well as all following ones, we suggest that you write `R` scripts (one per set of exercises or a combined one for the whole course) and store them in the `my_scripts` folder contained in the course materials. This folder already contains a script stub called `my_script.R` which you can use for getting started.

```{block, box.title = "1", box.body = list(fill = "white"), box.icon = "fa-star"}
To explore what `R` packages are out there that may be of interest for you, have a brief (!) look at the [`CRAN Task View`](https://cran.r-project.org/) section called *SocialSciences* and do a quick search for "regression" on [METACRAN](https://www.r-pkg.org/).
```

```{block, opts.label = "clues"}
 Although it may be tempting (there are so many interesting packages!), try not to spend more than 2 to 3 minutes on this (for now).
```

```{block, box.title = "2", box.body = list(fill = "white"), box.icon = "fa-star"}
The first simple coding task for this exercise is to install a few packages from `CRAN` (we will use those later on in the course). Please install the following packages: `remotes`, `dplyr`, `janitor`, `correlation` (*Note*: We will need a few more packages throughout this course, but we do not have to install all of them now). 
```

```{r second-exercise, solution = TRUE, eval = FALSE}
install.packages(c("remotes", "dplyr", "janitor", "correlation"))
```

```{block, box.title = "3", box.body = list(fill = "white"), box.icon = "fa-star"}
Now, let's load one of the packages you have just installed. Load the `remotes` package.
```

```{block, opts.label = "clues"}
You do not need to enclose the package name in quotes when loading it.
```

```{r third-exercise, solution = TRUE, eval = FALSE}
library(remotes)
```

```{block, box.title = "4", box.body = list(fill = "white"), box.icon = "fa-star"}
Some packages are not on `CRAN`. Another important source of `R` packages is *GitHub* (especially for development versions). So, let's install a package from there. Install the [`emo` package](https://github.com/hadley/emo) from *GitHub*. **NB**: To be able to install packages from *GitHub* on *Windows* machines, you will need to install [`Rtools`](https://cran.r-project.org/bin/windows/Rtools/) first.
```

```{block, opts.label = "clues"}
You can use a function from the `remotes` package for this. The required argument for the function for installing a package from *GitHub* needs to be in the form "user_name/repo_name" (i.e., the parts of the URL that come after github.com).
```

```{r fourth-exercise, solution = TRUE, eval = FALSE}
library(remotes)

install_github("hadley/emo")
```

```{block, box.title = "5", box.body = list(fill = "white"), box.icon = "fa-star"}
Check which packages are now installed on your system.
```

```{block, opts.label = "clues"}
You can use the *RStudio* interface or a function for this.
```

```{r fifth-exercise, solution = TRUE, eval = FALSE}
installed.packages()
```

```{block, box.title = "6", box.body = list(fill = "white"), box.icon = "fa-star"}
As a final exercise, add some comments to your script and save it (in the `my_scripts` folder).
```

```{block, opts.label = "clues"}
Comments in `R` start with #. Ideally, these should explain what the code you have written does. You can simply save the `R` script file via the *RStudio* GUI.
```

```{r sixth-exercise, solution = TRUE, eval = FALSE}
# Check installed packages
installed.packages()
```
